version: '3'
services:
  listing_service_db:
    container_name: search-request-app-db
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: search_request_db
    ports:
    - "5432:5432"